mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
    OrdersDataExportView,
    ProductViewSet,
    OrderViewSet,
    UserOrdersListView,
    UserOrdersExportView,
    create_product,
    create_order,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="products_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrderListView.as_view(), name="orders_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders-export"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order_detail"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("products/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders"),
    path("users/<int:user_id>/orders/export/", UserOrdersExportView.as_view(), name="user_orders_export"),
]

mysite/shopapp/templates/shopapp/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go">
</form>

{% block body %}

{% endblock %}

<div>
    {% now 'H:i' %}
</div>

<div>
    {% now 'l' as current_weekday %}
    {% trans "Today is" %} {{ current_weekday }}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Create Order" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Create a new order" %}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">{% trans "Create" %}</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">{% trans "Back to order list" %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Create Product" %}
{% endblock %}

{% block body %}
    <h1>{% translate "Create a new product" %}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">{% trans "Create" %}</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">{% trans "Back to product list" %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Groups List" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Groups" %}:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans "Create" %}</button>
        </form>
    </div>
    <div>
    {% if not groups %}
        <h3>{% trans "No groups yet" %}</h3>
    {% else %}
        <ul>
            {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                            {{ permission.name }}
                            (<code>{{ permission.codename }}</code>)
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Confirm delete" %} {{ object.name }}
{% endblock %}

{% block body %}
    <h1>{% trans "Are you sure, you want to delete" %} {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_detail' pk=object.pk %}">{% trans "Back to order" %} #{{ object.pk }}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans "Delete" %}</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Order list" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Orders" %}:</h1>
    {% if object_list %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_detail' pk=order.pk %}">{% trans "Details" %} #{{ order.pk }}</a></p>
                <p>{% trans "Order by" %} {% firstof order.user.first_name order.user.username %}</p>
                <p>{% trans "Promocode" %}: <code>{{ order.promocode }}</code></p>
                <p>{% trans "Delivery address" %}: {{ order.delivery_address }}</p>
                <div>
                    Products in order:
                </div>
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} for {{ product.price }}</li>
                        {% endfor %}
                    </ul>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>{% trans "No orders yet" %}</h3>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:order_create' %}">{% trans "Create a new order" %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Update Order" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Update order" %}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">{% trans "Update" %}</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_detail' pk=object.pk %}">{% trans "Back to order" %} #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Confirm archive" %} {{ object.name }}
{% endblock %}

{% block body %}
    <h1>{% trans "Are you sure, you want to archive" %} {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:products_details' pk=object.pk %}">{% trans "Back to product" %} #{{ object.pk }}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans "Archive" %}</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Create Product" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Create a new product" %}</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">{% trans "Create" %}</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">{% trans "Back to product list" %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Product" %} #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>{% trans "Product" %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% trans "Description" %}: <em>{{ product.description }}</em></div>
        <div>{% trans "Price" %}: {{ product.price }}</div>
        <div>{% trans "Discount" %}: {{ product.discount }}</div>
        <div>{% trans "Created_by" %}: {{ product.created_by }}</div>
        <div>{% trans "Archived" %}: {{ product.archived }}</div>
        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
        <h3>{% trans "Images" %}:</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                    <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>{% trans "No images uploaded yet" %}</div>
            {% endfor %}
        </div>
    </div>
    {% if 'shopapp.change_product' in perms and product.created_by == user or user.is_superuser == True %}
        <div>
            <a href="{% url 'shopapp:product_update' pk=product.pk %}">{% trans "Update product" %}</a>
        </div>
        <div>
            <a href="{% url 'shopapp:product_delete' pk=product.pk %}">{% trans "Archive product" %}</a>
        </div>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:products_list'  %}">{% trans "Back to products list" %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Products list" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Products" %}:</h1>
    {% if products %}
        <div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:products_details' pk=product.pk %}">{% trans "Name" %}: {{ product.name }}</a></p>
                <p>{% trans "Price" %}: {{ product.price }}</p>
                <p>{% trans "Discount" %}: {% firstof product.discount no_discount %}</p>
                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>{% trans "No products yet" %}</h3>
    {% endif %}
    <div>
        {% if 'shopapp.add_product' in perms %}
            <a href="{% url 'shopapp:product_create' %}">{% trans "Create a new product" %}</a>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load i18n %}
{% load cache %}

{% block title %}
    {% trans "Shop Index" %}
{% endblock %}

{% block body %}
<h1>{% trans "Hello Shop Index" %}</h1>

<div>
    <ul>
        {% trans "Call Right now" %}:
        {% for name, price in products %}
            <li>{{ name|title }} for {{ price }} $</li>
        {% empty %}
            {% trans "No products" %}
        {% endfor %}
    </ul>
</div>

<div>
    <ul>
        {% trans "Tomorrow" %}:
        {% for name, price in products %}
            <li>{{ name|title }} for {{ price|add:"2" }} $</li>
        {% empty %}
            {% trans "No products" %}
        {% endfor %}
    </ul>
</div>

<div>
    {% trans "Time running" %}: {{ time_running|floatformat:"0" }} {% trans "seconds" %}
</div>

{% cache 60 lorem %}
<div>
    {% lorem 3 p random %}
</div>
{% endcache %}

{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    User orders list
{% endblock %}

{% block body %}

    {% if object_list %}
        <h2>User {{ owner }} </h2>
        {% cache 300 userinfo owner.pk %}
        <h3> Have {{ count_orders }} orders:</h3>
        <div>
        <ul>
        {% for order in object_list %}
            <li>
                <p><a href="{% url 'shopapp:order_detail' pk=order.pk %}">Order id# {{ order.pk }}</a></p>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Products in order:
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} for {{ product.price }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </li>
        {% endfor %}
        </ul>
        </div>
        {% endcache %}
    {% else %}
        <h2>User {{ owner }} has no orders yet</h2>
    {% endif %}
    <p>Request by user: {{ user }}</p>
{% endblock %}