mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLoginView,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    ProfileUpdateView,
    ProfilesListView,
    ProfileView,
    HelloView
)

app_name = "myauth"

urlpatterns = [
    # path("login/", LoginView.as_view(
    #     redirect_authenticated_user=True,
    # ), name="login"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("about-me/update/<int:pk>", ProfileUpdateView.as_view(), name="profile-update"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
    path("profiles/", ProfilesListView.as_view(), name="profiles-list"),
    path("profiles/<int:pk>/", ProfileView.as_view(), name="profile-details"),
]

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


def avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "profiles/profile_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Profile(models.Model):
    class Meta:
        verbose_name = _("profile")
        verbose_name_plural = _("profiles")

    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_("user"))
    bio = models.TextField(max_length=500, blank=True, verbose_name=_("bio"))
    agreement_accepted = models.BooleanField(default=False, verbose_name=_("agreement accepted"))
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path, verbose_name=_("avatar"))

mysite/myauth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import reverse, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView
from django.views import View
from random import random
from .models import Profile
import logging


logger = logging.getLogger(__name__)


class HelloView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        return HttpResponse("<h1>Hello world</h1>")


class MyLoginView(LoginView):
    template_name = "myauth/login.html"
    redirect_authenticated_user = True

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user_name = form.cleaned_data.get('username')
            logger.info(f'авторизовался пользователь: {user_name}')
        return super().post(self, request, *args, **kwargs)


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class ProfilesListView(ListView):
    template_name = "myauth/profiles-list.html"
    model = Profile
    context_object_name = "profiles"


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class ProfileUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_staff:
            return True
        profile_obj = get_object_or_404(Profile, pk=self.kwargs.get('pk'))
        if profile_obj.pk == self.request.user.profile.pk:
            return True

    model = Profile
    fields = "bio", "avatar"
    template_name = "myauth/profile_update_form.html"
    success_url = reverse_lazy("myauth:about-me")


class ProfileView(DetailView):
    template_name = "myauth/profile-details.html"
    model = Profile
    context_object_name = "profile"


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load i18n %}
{% load cache %}

{% block title %}
    {% trans "About me" %}
{% endblock %}

{% block body %}
    <h1>{% trans "User info" %}</h1>
    {% if user.is_authenticated %}
        {% cache 60 userinfo user.username %}
        <h2>{% trans "Detail" %}</h2>
        {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}"/>
        {% else %}
            <div>{% trans "No images uploaded yet" %}</div>
        {% endif %}
        <p>{% trans "Username" %}: {{ user.username }}</p>
        <p>{% trans "First name" %}: {{ user.first_name }}</p>
        <p>{% trans "Last name" %}: {{ user.last_name }}</p>
        <p>{% trans "Email" %}: {{ user.email }}</p>
        <p>{% trans "Bio" %}: {{ user.profile.bio }}</p>
        {% endcache %}
        <div>
            <a href="{% url 'myauth:profiles-list' %}">{% trans "Profiles list" %}</a>
        </div>
        <div>
            <a href="{% url 'myauth:profile-update' pk=user.profile.pk %}">{% trans "Update profile" %}</a>
        </div>
    {% else %}
        <h2>{% trans "User is anonymous" %}</h2>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Login" %}
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">{% trans "Login" %}</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile-details.html
{% extends 'myauth/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Profile Details" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Profile info" %}</h1>
    {% if profile.avatar %}
        <img src="{{ profile.avatar.url }}" alt="{{ profile.avatar.name }}"/>
    {% else %}
        <div>{% trans "No images uploaded yet" %}</div>
    {% endif %}
    <p>{% trans "Username" %}: {{ profile.user.username }}</p>
    <p>{% trans "First name" %}: {{ profile.user.first_name }}</p>
    <p>{% trans "Last name" %}: {{ profile.user.last_name }}</p>
    <p>{% trans "Email" %}: {{ profile.user.email }}</p>
    <p>{% trans "Bio" %}: {{ profile.bio }}</p>
    <div>
        <a href="{% url 'myauth:profiles-list' %}">{% trans "Profiles list" %}</a>
    </div>
    {% if user.is_staff or user.profile.pk == profile.pk %}
        <div>
            <a href="{% url 'myauth:profile-update' pk=profile.pk %}">{% trans "Update profile" %}</a>
        </div>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Update Profile" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Update profile" %}</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">{% trans "Update" %}</button>
        </form>
    </div>
    <div>
        <a href="{% url 'myauth:about-me' %}">{% trans "Back to profile" %}</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/profiles-list.html
{% extends 'myauth/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Profiles list" %}
{% endblock %}

{% block body %}
    <h1>{% trans "Profiles" %}:</h1>
    {% if profiles %}
        <div>
        {% for profile in profiles %}
            {% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="{{ profile.avatar.name }}"/>
            {% else %}
                <div>{% trans "No images uploaded yet" %}</div>
            {% endif %}
            <div>
                <a href="{% url "myauth:profile-details" pk=profile.pk %}">
                    <p>{% trans "name" %}: {{ profile.user.username }}</p>
                </a>
            </div>
            <br><br>
        {% endfor %}
        </div>
    {% else %}
        <h3>{% trans "No profiles yet" %}</h3>
    {% endif %}
{% endblock %}