mysite/blogapp/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleDetailView,
    LatestArticleFeed,
)

app_name = "blogapp"

urlpatterns = [
    path("articles/", ArticleListView.as_view(), name="articles"),
    path("articles/create/", ArticleCreateView.as_view(), name="article_create"),
    path("articles/<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("articles/<int:pk>/update/", ArticleUpdateView.as_view(), name="article_update"),
    path("articles/<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("articles/latest/feed/", LatestArticleFeed(), name="articles-feed"),
]

mysite/blogapp/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField(null=False, blank=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=40, null=False, blank=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, null=False, blank=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=True)
    content = models.TextField(null=False, blank=True)
    pub_date = models.DateTimeField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name="articles")

    def get_absolute_url(self):
        return reverse("blogapp:article_detail", kwargs={"pk": self.pk})

mysite/blogapp/forms.py
from django import forms
from .models import Article
from django.forms import ModelForm


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = "title", "content", "pub_date", "author", "category", "tags",

mysite/blogapp/views.py
import os.path
from django.contrib.syndication.views import Feed
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.urls import reverse, reverse_lazy
from .forms import ArticleForm
from .models import Article
import logging


logger = logging.getLogger(__name__)


class ArticleListView(ListView):

    template_name = "blogapp/articles_list.html"
    # model = Article
    queryset = (
        Article.objects
        .select_related("author")
        .prefetch_related("tags")
        .prefetch_related("category")
        .defer("content", "author__bio")
    )

    def dispatch(self, request, *args, **kwargs):
        logger.info('Вызывается Список статей')
        return super().dispatch(request, *args, **kwargs)


class ArticleDetailView(DetailView):
    template_name = "blogapp/article_detail.html"
    queryset = (
        Article.objects
        .select_related("author")
        .prefetch_related("tags")
        .prefetch_related("category")
    )

    def dispatch(self, request, *args, **kwargs):
        u = self.request.user
        i = os.path.split(self.request.path)
        i_1 = os.path.split(i[0])
        i = i_1[1]
        logger.info(f'{u} вызывает статью с ID# {i}')
        return super().dispatch(request, *args, **kwargs)


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy("blogapp:articles")

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        u = self.request.user
        if form.is_valid():
            logger.info(f'{u} создал новую статью')
        return super().post(request, *args, **kwargs)


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "blogapp:article_detail",
            kwargs={"pk": self.object.pk}
        )


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy("blogapp:articles")


class LatestArticleFeed(Feed):
    title = "Blog articles (latest)"
    description = "Updates on changes and addition blog articles"
    link = reverse_lazy("blogapp:articles")

    def items(self):
        return (
            Article.objects
            .filter(pub_date__isnull=False)
            .order_by("-pub_date")[:5]
        )

    def item_title(self, item: Article):
        return item.title

    def item_description(self, item: Article):
        return item.content[:200]

    def item_link(self, item: Article):
        return reverse("blogapp:article_detail", kwargs={"pk": item.pk})

mysite/blogapp/templates/blogapp/article_confirm_delete.html
{% extends 'blogapp/base.html' %}
{% load i18n %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure, you want to delete {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'blogapp:article_detail' pk=object.pk %}">Back to article #{{ object.pk }}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

mysite/blogapp/templates/blogapp/article_detail.html
{% extends 'blogapp/base.html' %}
{% load i18n %}

{% block title %}
    Article #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Article {{ object.pk }}</h1>
    <div>
        <p>Title: {{ object.title }}</p>
        <p>Article: <code>{{ object.content }}</code></p>
        <p>Publicate date: {{ object.pub_date }}</p>
        <p>Author: {{ object.author }}</p>
        <div>
            Tags in article:
        </div>
            <ul>
                {% for tag in object.tags.all %}
                    <li>{{ tag.name }}</li>
                {% endfor %}
            </ul>
    </div>
    <div>
        <a href="{% url 'blogapp:article_update' pk=article.pk %}">Update Article</a>
    </div>
    <div>
        <a href="{% url 'blogapp:article_delete' pk=article.pk %}">Delete Article</a>
    </div>
    <div>
        <a href="{% url 'blogapp:articles' %}">Back to Article</a>
    </div>
{% endblock %}

mysite/blogapp/templates/blogapp/article_form.html
{% extends 'blogapp/base.html' %}
{% load i18n %}

{% block title %}
    Create Article
{% endblock %}

{% block body %}
    <h1>Create a new article</h1>
    <div>
        <p>!Date format: YYYY-MM-DD hh:mm:ss!</p>
        <form method="post">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'blogapp:articles' %}">Back to order list</a>
    </div>
{% endblock %}

mysite/blogapp/templates/blogapp/article_update_form.html
{% extends 'blogapp/base.html' %}
{% load i18n %}

{% block title %}
    Update Order
{% endblock %}

{% block body %}
    <h1>Update order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'blogapp:article_detail' pk=object.pk %}">Back to order #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/blogapp/templates/blogapp/articles_list.html
{% extends 'blogapp/base.html' %}
{% load i18n %}

{% block title %}
    Article List
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'blogapp:article_create' %}">Create a new Article</a>
    </div>
    <h1>Articles:</h1>
    {% if object_list %}
        <div>
        {% for article in object_list %}
            <p><a href="{% url 'blogapp:article_detail' pk=article.pk %}">ID: #{{ article.pk }}</a></p>
            <p>title: {{ article.title }}</p>
            <p>pub_date: {{ article.pub_date }}</p>
            <p>author: {{ article.author }}</p>
            <p>category: {{ article.category }}</p>
            <div>
                Tags in Article:
                <ul>
                    {% for tag in article.tags.all %}
                        <li>{{ tag.name }}</li>
                    {% endfor %}
                </ul>
            </div>
            <br>
        {% endfor %}
        </div>
    {% else %}
        <h3>{% trans "No articles yet" %}</h3>
    {% endif %}
{% endblock %}